service: serverless-framework-starter

plugins:
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, file(./config/config.${self:provider.stage}.json):region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
    SOMEVAL: ${file(./config/config.${self:provider.stage}.json):someval}
  versionFunctions: false
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"

functions:
  test-func:
    ${file(src/test-func/functions.yml)}
  test-func1:
    ${file(src/test-func/functions1.yml)}

