service: serverless-framework-starter

plugins:
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    port: 4000
  config-file: ${file(./config/config.${opt:stage, 'dev'}.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.config-file:stage, 'dev'}
  region: ${opt:region, self:custom.config-file:region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
    SOMEVAL: ${self:custom.config-file.someval}
  versionFunctions: false
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"

functions:
  helloWorld:
    ${file(src/helloWorld/functions.yml)}
